### ISSUE TITLE
Method relation_subgathers being called even if no records present which is affecting the query performance

### ISSUE THREAD

**Issue by gekkaBee** [divad1196/odoo_graphql#11]
In files utils.py, line 224 the method relation_subgathers is begin called even if the parent records in empty which has affected the query performance. The search on the each relational_data are being called without any domain if the records is empty which is causing it to retrieve all the records.

 subgathers = relation_subgathers(records, relational_data, variables=variables) if records else {}  would be a proper fix for it.

Please let me know if I'm missing something for this be the intended behavior.

**Comment by divad1196** [comment]
@gekkaBee yes, you are missing things.
The function will loop on subfields, if there is none there won't be any loop executed.

There is certainly ways to improve performance but with less maintainable code.
For exemple, I could avoid calling the function with a if, but it means I then need to have the condition outside of the function matching the one in the function everywhere.
Also, having a single type for return (always a dict, at worst an empty one instead of returning None) avoid extra type checks and runtime errors.

I will update/make the issue reporting rules, but I cannot start explaining things to everyone. If you don't have significant proof/benchmark of performance issue, I don't know a single repository owner that would have taken the time to respond.
In your case, you could have made a benchmark with the current code and the variation you are proposing, trying small queries as well as big ones (lot a record or with lot of deeply nested fields or both) in both cases. I don't think you would have seen any particular gain.

Edit: I forgot to answer the second point, but once again -> loop not executed and `.mapped` on empty recordset is also an empty iterable. 

Have a nice day.

**Comment by gekkaBee** [comment]
My point being, why loop on the subfield when the parent records is empty.

Yes mapping on an empty records, will return empty iterable and sub_records_ids will be []
`sub_records_ids = records.mapped(fname).ids`

but the method parse_model_field for that iteration will have still be called with empty list ids parameter,
and the code
`# Retrieve records`
`domain = make_domain(domain or [], ids)w`
`records = model.search(domain, **kwargs)`

in the method retrieve_records will be triggered with domain [] which will retrieve all child records unnecessarily. 

Please check it once. I used the suggested change and it has significantly improved performance for me with no issues till now. I don't expect you to make the change or respond further but please take a look at that logic whenever you're free. Thank you. 

Further I'd to appreciate you responding to this and making this graphql extension for odoo.

Nice day to you too.

**Comment by divad1196** [comment]
@gekkaBee already understood and responded.

I will be strict, you have to understand I cannot start making exceptions and respond/test everything from anyone.
If you want something more, benchmark it and do a proper issue reporting, I would be glad to check it then and only then.
