### ISSUE TITLE
Graphlql schema cannot be loaded using Odoo 17

### ISSUE THREAD

**Issue by swolf91** [divad1196/odoo_graphql#30]
Using the newly created odoo 17 the plugin works so far but the graphlq schema for the included graphiql or other tools like postman cannot be loaded anymore.

<img width="646" alt="image" src="https://github.com/divad1196/odoo_graphql/assets/1949169/1ef806c9-0cfb-4604-9a6f-20068763864a">

I get the following error:

```json
{
  "errors": [
    {
      "message": "Invalid or incomplete schema, unknown type: IapAccountInfo. Ensure that a full introspection query is used in order to build a client schema.",
      "stack": "d@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:334503\ng@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:335050\nye@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:229567\nMt@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:245621\ngetFields@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:244986\njn@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:273018\nPn@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:270420\nmo@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:1:333934\n@http://localhost:8069/odoo_graphql/static/js/graphiql.min.js:29:231674"
    }
  ]
}
```

**Comment by divad1196** [comment]
Hi @swolf91 
Sorry, I had no time to check your issue before.

The module is currently not migrated into V17. Pointing out this kind of issue is not useful.

We just entered the V17 (btw, it should be available only for new users) which is usually a quite unstable period for Odoo. I won't rush migrating the module in the early stage of V17.

The module will be officially migrated begining 2024. This may be reconsidered if there is a **real**, business critic, need for an organisation.

**Comment by maxtkachenko889** [comment]
Hi to all! Thanks for the great module, I'm waiting for version 17 too, when can I test it?

**Comment by divad1196** [comment]
@swolf91 and @maxtkachenko889 
The migration is officially done. I will close this issue but feel free to create a new one if you encounter any issue.

---
## Changes made

The issue encountered was linked to Transient Model being filtered out of the graphql schema definition while the fields referencing such models were still in the schema. I don't exactly remember why I hidded transient models, and since it is not causing security issue, I removed this filtering.

---
## Additional Note

### Usual migration period
I would have preferred to wait until february/march which is when Odoo usually stabilizes the migration process. The reasons are:
- There are more chance that Odoo introduce breaking changes until then
- People that will already be on V17 are new to Odoo. Prematurely bloatering your Odoo with modules and service inter-connectivity is usually bad and people tend to jump to fast on it. From my experience working as Odoo integrator, half a year using Odoo is not enough for most people to be reasonable about it.

### Thankings
I would like to thank all people that contribute by reporting bugs, proposing features, or simply by using this module.
