### ISSUE TITLE
__typename does not display

### ISSUE THREAD

**Issue by Kosnstantin** [divad1196/odoo_graphql#31]
When I use any queries with __typename (i need it in Apollo, but i can't work with it), for example:
query New {
  ProductProduct {
    __typename
    id
    name
  }
}
I have this error:
{
  "data": null,
  "errors": {
    "message": "'__typename'"
  }
}
why?

**Comment by divad1196** [comment]
Because
1. this is how you would get from RPC: private fields (starting with underscore) cannot be accessed (nor called in RPC).
Exposing them would be a security issue since all Odoo developer has been following this convention.
2. I only allow introspection for the graphiql editor, not the rest (performance and simplicity).


This can be argue if there are some real scenarios/use-cases.

**Comment by Kosnstantin** [comment]
All right. Can you help me to realize this functionality?

**Comment by Kosnstantin** [comment]
I am making a request using Apollo and because of this I am getting an error, how can I solve this problem from the backend

**Comment by divad1196** [comment]
> All right. Can you help me to realize this functionality?

First explain the need more precisely so we can discuss it. Not being able to call it is not a reason:
Why would you need the __typename? What is your query? ...

Also, please edit your comment instead of adding a new one everytime.

**Comment by Kosnstantin** [comment]
> > All right. Can you help me to realize this functionality?
> 
> First explain the need more precisely so we can discuss it. Not being able to call it is not a reason: Why would you need the __typename? What is your query? ...
> 
> Also, please edit your comment instead of adding a new one everytime.

I'm making queries using Apollo. And when it makes any query, it substitutes automatically __typename to almost all query strings, because of this I get an error. I can't disable this function with automatic __typename substitution, because I need it to work with the cache. You can see an example of one of the requests above. I make a query like this:
query New {
ProductProduct {
id
name
}
}
Apollo interprets it like this:
query New {
__typename
ProductProduct {
__typename
id
__typename
name
}
}
This is just an example, there are many more requests.

**Comment by divad1196** [comment]
@Kosnstantin I found 2 links:
* [The __typename field](https://www.apollographql.com/docs/apollo-server/schema/schema/#the-__typename-field) which is the short explanation given by Apollo and honestly not convincing about the reasons.
* [__typename in query response](https://github.com/apollographql/apollo-client/issues/1913#issuecomment-336376513)
  Many don't seem happy with this choice which can be deactivated by the client.
 
As explained in the latter link, you can make it work with the `addTypename` client option. This will make your code work, so this is not a bug but a feature request.

---

For the following statement:
> because I need it to work with the cache
Why do you "need" it ? What can possibly not work for it to be needed?

To make it clear: I am **not** against adding support for it. If it was preventing the use of Apollo, this would have been a reason, solely because I know how Apollo client is popular. But this is is not the case. 

I cannot, and will not, do changes from anyone simply asking for them without a properly described need and/or benefit. Otherwise, I would soon enough be requested any small adjustement required for any library and this will impact the quality of the latter.

So, please, **develop on the reason(s)** why this should be added on this module. Also consider using proper formatting (even for queries) and give sources (articles, benchmarks, .. I should not have to fact-check you sayings).
Thank you for your understanding, I will be waiting for your response. In the meantime, have a nice day.

**Comment by Kosnstantin** [comment]
> @Kosnstantin I found 2 links:
> 
>     * [The __typename field](https://www.apollographql.com/docs/apollo-server/schema/schema/#the-__typename-field) which is the short explanation given by Apollo and honestly not convincing about the reasons.
> 
>     * [__typename in query response](https://github.com/apollographql/apollo-client/issues/1913#issuecomment-336376513)
>       Many don't seem happy with this choice which can be deactivated by the client.
> 
> 
> As explained in the latter link, you can make it work with the `addTypename` client option. This will make your code work, so this is not a bug but a feature request.
> 
> For the following statement:
> 
> > because I need it to work with the cache
> > Why do you "need" it ? What can possibly not work for it to be needed?
> 
> To make it clear: I am **not** against adding support for it. If it was preventing the use of Apollo, this would have been a reason, solely because I know how Apollo client is popular. But this is is not the case.
> 
> I cannot, and will not, do changes from anyone simply asking for them without a properly described need and/or benefit. Otherwise, I would soon enough be requested any small adjustement required for any library and this will impact the quality of the latter.
> 
> So, please, **develop on the reason(s)** why this should be added on this module. Also consider using proper formatting (even for queries) and give sources (articles, benchmarks, .. I should not have to fact-check you sayings). Thank you for your understanding, I will be waiting for your response. In the meantime, have a nice day.

Good afternoon. I am not asking to extend your module that is uploaded on GitHub. I could use your help in adding this function to the module I have installed. The problem is that if I add addTypename: false, as indicated in the link you attached above, I get a lot of requests from Apollo, which is very stressful on the server, and it becomes incredibly difficult to work with Odoo. And if I add addTypename: true, then I get this error
{
  "data": null,
  "errors": {
    "message": "'__typename'"
  }
}
So it's as if the problem is that Apollo automatically adds "'__typename'" to the query (almost every field and model), and the query doesn't know how to handle "'__typename'". And inside the module I don't quite understand how to extend the functionality, or rather add the ability to properly handle queries with "'__typename'".  Can you help me or tell me what files I need to modify to get what I want? Thank you for your reply, I apologize for the wait.

**Comment by divad1196** [comment]
@Kosnstantin (Please, watch your formatting...)

Sorry but I won't help people working on their fork. 
* If I help one person, I will have to help everyone
* Then, once I add features on this repository or migrate the code, I will be asked for help once again
* I also don't want to encourage having modified forks of this module (hence the license). I don't want to make it a "feature competition".
* This is also very egoistic, you are probably not the only one that would like this feature.

I already refused multiple people (e.g. #3 ), even those who wanted to pay me for the job. I am willing to still help people find with tips (like how you can disable the cache on Apollo) but that is it.

So, I **MAY** define the pros/cons myself one day and decide to implement it myself, but I may also never consider it at all or be wrong about my reasons. So, if someone want a feature, they must either try to convice of the benefits of adding it or do it themselves _for themselves_ (I won't accept a PR if the benefits were not discussed before it's developement).

If you are not willing to contribute (feature request, bug report, ..), then I am afraid **I will have to close this issue** and wish you good luck. You are welcome to open a new issue whenever you encounter any bug, have a question/recommendation about something not clear in the documentation or want to make a proper feature request.

Have a nice day.

---

By the way, here are some more information about your issue:
* You can still implement caching yourself. While Apollo does some caching for you, it will never be optimal.
* If the limitation was the UX (which is apparently not the case), then there may be a lot to improve on the frontend code.
* If the limitation is on the server side, then don't think that caching will save you
  * Cache won't be shared across users, nor browser and probably not even between the browser's tabs (except if using the storage which I doubt is done natively by Apollo)
  * Ain't you just making to many requests?
    * Do you [abort your requests](https://stackoverflow.com/questions/31061838/how-do-i-cancel-an-http-fetch-request) when not useful anymore ? (e.g. Complete as you type scenario)
    * Do you debounce your requests when multiple ones are run simulteanously ?
    * ...
  * You might be at risk for (D)DoS attacks (not because of this module, just because this might mean that you have too few resources available)
  You might consider increasing the RAM of your Odoo (This is what this module requires the most since it needs to store the whole payload to return it). Increasing the number of workers (or vCPU) would help if you will have a lot of simulteanous connection. If you have control over you Odoo installation, you might want to make your Odoo stateless with OCA's modules (the one that allow external storage of filestore and the one the one that stores sessions in redis) and then scale the number of Odoo install you have when you need.
  
Note that, I am just giving you these informations as a last advice/tip if you don't want to contribute by forumlating a proper requests with the benefits for the users.
