### ISSUE TITLE
cannot import name 'VariableNode'

### ISSUE THREAD

**Issue by troublero** [divad1196/odoo_graphql#7]
I am having an issue of making sure I can access the library that process the graphql message

 File "/home/thomas/workspace/Orr-Odoo/odoo/src/private-addons/odoo_graphql/controllers/graphql.py", line 4, in <module>
    from ..utils import handle_graphql
  File "/home/thomas/workspace/Orr-Odoo/odoo/src/private-addons/odoo_graphql/utils.py", line 7, in <module>
    from graphql.language.ast import (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thomas/workspace/14.0/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/thomas/workspace/14.0/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ImportError: cannot import name 'VariableNode' from 'graphql.language.ast' (/usr/local/lib/python3.8/dist-packages/graphql/language/ast.py)

so I am trying to make sure I have the all the libraries installed

**Comment by divad1196** [comment]
@troublero I cannot help you with it: as you said, your issue is with the library, not the module.
If you managed to install the module, this means you have the `graphql-core` library installed, otherwise Odoo wouldn't have let you install the module. All the libraries you need are referenced in the `__manifest__.py` file, and in this case you only need `graphql-core`.
I just tried a fresh install (`python3.8 -m pip install graphql-core`), got the version `graphql-core-3.2.3` and this worked correctly.

I would recommend you to just open the python interpreter and check the import manually
```python
from graphql.language.ast import (
    VariableNode,
    ValueNode,
    ObjectValueNode,
    ListValueNode,
    IntValueNode,
    FloatValueNode,
)
```
This would give you a first hint. Secondly, I would make a fresh install of the module. This may also be related to how you launch your Odoo.
If you still have issues, you may contact the maintainers of `graphql-core` library, even though this is an issue by your side and they will probably not help you. In any case, this repository is not the place to ask question regarding your python/Odoo environment.

Good luck and have a nice day.
